In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
print(arr.ndim)
print(type(arr))

[1 2 3 4 5]
(5,)
1
<class 'numpy.ndarray'>


In [4]:
arr1=np.array(42)
print(arr1)
print(arr1.shape)
print(arr1.ndim)

42
()
0


In [5]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [6]:
arr3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
3


In [7]:
arr4=np.array([1,2,3,4], ndmin=5)
print(arr4)
print('number of dimnsion:',arr4.ndim)
print(arr4.shape)

[[[[[1 2 3 4]]]]]
number of dimnsion: 5
(1, 1, 1, 1, 4)


In [8]:
print(arr1,arr[0],arr2[0,1],arr3[0,1,2])

42 1 2 6


In [9]:
print(arr2)
print(arr2[-2,-1])

[[1 2 3]
 [4 5 6]]
3


In [10]:
arr4=np.array([1,2,3,4,5,6,7])
print(arr4[1:5])
print(arr4[-5:-1])
print(arr4[2:])
print(arr4[:4])
print(arr4[0:7:2])
print(arr4[::2])

[2 3 4 5]
[3 4 5 6]
[3 4 5 6 7]
[1 2 3 4]
[1 3 5 7]
[1 3 5 7]


In [11]:
arr5=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
print(arr5[1,1:4])
print(arr5[0:2,2])
print(arr5[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [13]:
print(arr5.dtype)

int64


In [14]:
arr6=np.array(['apple','banana','cherry'])
print(arr6.dtype)

<U6


In [15]:
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [16]:
arr=np.array([1,2,3,4],dtype='i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [17]:
arr=np.array(['a','2',3],dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [18]:
arr=np.array([3.47,2.141,4.15])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[3 2 4]
int32


In [19]:
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [20]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [21]:
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)
x[0]=125
print(arr)

[42  2  3  4  5]
[42  2  3  4  5]
[125   2   3   4   5]


In [22]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [23]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


In [24]:
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[1 2 3 4 5 6]
1
(6,)


In [25]:
arr=np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [26]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [27]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [28]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [29]:
for x in arr:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [30]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [31]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [32]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [33]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
arr=np.array([1,2,3,4,5,6,7])
newarr=np.array_split(arr,3)
print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2, 3]), array([4, 5]), array([6, 7])]
[1 2 3]
[4 5]
[6 7]


In [35]:
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)
print(newarr[0])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]


In [36]:
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [37]:
arr1=np.array(['banana','cherry','apple'])
print(np.sort(arr1))

['apple' 'banana' 'cherry']


In [38]:
arr2=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr2))

[[2 3 4]
 [0 1 5]]


In [39]:
from numpy import random
x=random.randint(100)
print(x)

58


In [40]:
x1=random.rand()
print(x1)

0.5190819011623135


In [41]:
x2=random.randint(100,size=(3,5))
print(x2)

[[19 52 63 11 67]
 [12 87 79 93 47]
 [65 73 31 63 73]]


In [43]:
x3=random.rand(3,5)
print(x3)

[[0.43952361 0.34580344 0.80316688 0.6022057  0.27593021]
 [0.00730286 0.0467544  0.8474013  0.0767207  0.14018425]
 [0.35174487 0.05304501 0.75703122 0.93567884 0.86282184]]


In [44]:
a=np.array([[3,2,4],[5,0,1],[2,5,8]])
b=np.array([[1,0,5],[2,3,7],[6,4,5]])
print(a+2)
print(a-1)
print(a*5)
print(a/2)

[[ 5  4  6]
 [ 7  2  3]
 [ 4  7 10]]
[[ 2  1  3]
 [ 4 -1  0]
 [ 1  4  7]]
[[15 10 20]
 [25  0  5]
 [10 25 40]]
[[1.5 1.  2. ]
 [2.5 0.  0.5]
 [1.  2.5 4. ]]


In [45]:
c=a+b
print(c)

[[ 4  2  9]
 [ 7  3  8]
 [ 8  9 13]]


In [46]:
d=a-b
print(d)

[[ 2  2 -1]
 [ 3 -3 -6]
 [-4  1  3]]


In [47]:
e=a*b
print(e)

[[ 3  0 20]
 [10  0  7]
 [12 20 40]]


In [48]:
a=np.array([[3,2,4],[5,0,1],[2,5,8]])
print(a)
ta=np.transpose(a)
print(ta)

[[3 2 4]
 [5 0 1]
 [2 5 8]]
[[3 5 2]
 [2 0 5]
 [4 1 8]]


In [49]:
a=np.arange(5,50,2)
print(a)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median:',np.median(a))

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
Mean : 27.0
Standard deviation : 13.2664991614216
Median: 27.0


In [51]:
print('Min:',np.min(a))
print('Max:',np.max(a))

Min: 5
Max: 49


In [52]:
a=np.array([[3,2,4],[10,0,1],[7,5,8]])
print(a)
print('Min:',np.min(a,axis=0))
print('Max:',np.max(a,axis=1))

[[ 3  2  4]
 [10  0  1]
 [ 7  5  8]]
Min: [3 0 1]
Max: [ 4 10  8]


In [53]:
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))
print(x)

[7 5 7 5 5 5 7 5 7 7 7 7 3 3 7 3 5 7 7 3 5 7 5 7 3 7 7 3 7 7 7 5 7 7 7 5 5
 7 7 7 7 5 5 5 7 7 7 7 5 5 7 3 7 5 7 5 7 7 5 7 5 7 7 5 7 7 5 7 5 7 7 5 5 3
 3 7 3 5 5 7 7 7 5 5 7 7 7 5 7 5 3 5 7 7 5 7 5 5 5 3]


In [54]:
y=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(3,5))
print(y)

[[5 7 5 7 5]
 [5 7 7 3 7]
 [7 7 5 5 5]]


In [56]:
x=random.normal(size=(2,3))
print(x)

[[-0.05762647  0.35993055 -0.08373844]
 [ 0.20709361 -0.3097182   1.25647745]]


In [57]:
y=random.normal(loc=1,scale=2,size=(2,3))
print(y)

[[-0.93502261 -2.36000776 -3.89691071]
 [ 1.68664506  4.92156635 -0.1057507 ]]
